export const FORM_SUBMIT= 'FORM_SUBMIT';
export const FORM_SUBMIT_RESULT= 'FORM_SUBMIT_RESULT';


export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const REGISTER_PATIENT = 'REGISTER_PATIENT';
export const REGISTER_PATIENT_RESPONSE = 'REGISTER_PATIENT_RESPONSE';

export const REGISTER_DOCTOR = 'REGISTER_DOCTOR';
export const REGISTER_DOCTOR_RESPONSE = 'REGISTER_DOCTOR_RESPONSE';

export const REGISTER_STORE_KEEPER = 'REGISTER_STORE_KEEPER';
export const REGISTER_STORE_KEEPER_RESPONSE = 'REGISTER_STORE_KEEPER_RESPONSE';