export const FORM_SUBMIT= 'FORM_SUBMIT';
export const FORM_SUBMIT_RESULT= 'FORM_SUBMIT_RESULT';


export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const REGISTER_PATIENT = 'REGISTER_PATIENT';
export const REGISTER_PATIENT_RESPONSE = 'REGISTER_PATIENT_RESPONSE';

export const REGISTER_DOCTOR = 'REGISTER_DOCTOR';
export const REGISTER_DOCTOR_RESPONSE = 'REGISTER_DOCTOR_RESPONSE';

export const REGISTER_STORE_KEEPER = 'REGISTER_STORE_KEEPER';
export const REGISTER_STORE_KEEPER_RESPONSE = 'REGISTER_STORE_KEEPER_RESPONSE';

export const FETCH_PROFILE_REQUEST="FETCH_PROFILE_REQUEST"
export const FETCH_PROFILE_RESPONSE="FETCH_PROFILE_RESPONSE"

export const SUBMIT_PROFILE_REQUEST="SUBMIT_PROFILE_REQUEST"
export const SUBMIT_PROFILE_RESPONSE="SUBMIT_PROFILE_RESPONSE"
//
export const FETCH_VISIT_NOTES = "FETCH_VISIT_NOTES"
export const FETCH_MEDICAL_HISTORY = "FETCH_MEDICAL_HISTORY"
export const SUBMIT_MEDICAL_HISTORY = "SUBMIT_MEDICAL_HISTORY"
export const FETCH_VISIT_NOTES_RESPONSE = "FETCH_VISIT_NOTES_RESPONSE"
export const FETCH_MEDICAL_HISTORY_RESPONSE = "FETCH_MEDICAL_HISTORY_RESPONSE"
export const SUBMIT_MEDICAL_HISTORY_RESPONSE = "SUBMIT_MEDICAL_HISTORY_RESPONSE"


export const FETCH_UPCOMING_APPOINTMENTS = "FETCH_UPCOMING_APPOINTMENTS"
export const CANCEL_APPOINTMENT="CANCEL_APPOINTMENT"
export const SUBMIT_APPOINTMENT="SUBMIT_APPOITNEMNT"
export const CHECK_AVAILIBILITY="CHECK_AVAILABILITY"
export const FETCH_UPCOMING_APPOINTMENTS_RESPONSE = "FETCH_UPCOMING_APPOINTMENTS_RESPONSE"
export const CANCEL_APPOINTMENT_RESPONSE="CANCEL_APPOINTMENT_RESPONSE"
export const SUBMIT_APPOINTMENT_RESPONSE="SUBMIT_APPOITNEMNT_RESPONSE"
export const CHECK_AVAILIBILITY_RESPONSE="CHECK_AVAILABILITY_RESPONSE"

export const FETCH_PATIENT_EQUIPMENTS="FETCH_PATIENT_EQUIPMENTS"
export const FETCH_EQUIPMENTS="FETCH_EQUIPMENTS"
export const REQUEST_EQUIPMENT="REQUEST_EQUIPMENT"
export const FETCH_PATIENT_EQUIPMENTS_RESPONSE="FETCH_PATIENT_EQUIPMENTS_RESPONSE"
export const FETCH_EQUIPMENTS_RESPONSE="FETCH_EQUIPMENTS_RESPONSE"
export const REQUEST_EQUIPMENT_RESPONSE="REQUEST_EQUIPMENT_RESPONSE"


export const FETCH_BILLS="FETCH_BILLS"
export const FETCH_BILLS_RESPONSE="FETCH_BILLS_RESPONSE"